# The Perceptron

**This tutorial is adapted from [Damir Cavar](http://damir.cavar.me/) and Callie Federer tutorial**

A perceptron is simple model that can help us solve such a problem given enough data. **The perceptron can be defined as an algorithm for supervised binary classification.**

Let's imagine we have to predict whether your friend, Mbali, would be going for a workout or not. We have the following things to take into account:

- #### Weather (Sunny or Rainy) ?
- #### Time of Day (Morning or Evening) ?
- #### Energy Level (Energized) ?

<img src="resources/perceptron_cartoon.png" style="max-width:100%; width: 70%; max-width: none">

Perceptrons are made up of three components, namely:

    - The input: What we serve the perceptron with for inference
    - The input weights: Our associated weighting for each input feature
    - The activation function: A binary threshold function (Fire or No Fire!)
    
Define perceptron mathematically here...

## Example: To Gym or Not To Gym

We import *numpy* and define our *activation* function.

In [1]:
import numpy as np

def bactivation(z):
    if z == 0.5:
        return 1
    else: return 0

Here, we define our example data **input** $x$ 

In [8]:
weather = 0
evening = 1
energized = 1
x = np.array([weather, evening, energized])

Furthermore, we define the corresponding **weights** $w$, and **bias** $b$ of our perceptron $p$:

In [3]:
w = np.array([0.5, 0.5, 0])
b = 0

Our perceptron would compute $p$ as the **dot-product** $w \cdot x$ and add the **bias** $b$ to it. Subsequently, the activation function defined above will convert this $p$ value to the **activation value** $a$ of the unit:

In [5]:
p = w.dot(x) + b
a = bactivation(p)

Let's see what we get:

In [9]:
print("Perceptron Value (p):", p)
print("Activation Value of Perceptron (a):", a)

Perceptron Value (p): 0.5
Activation Value of Perceptron (a): 1


### Mini-Assignments

Provide an instance $x$ to the perceptron $p$, where your friend, Mbali, feels energized, but it's the evening and it's raining?

## Logic Gates (AND, OR) with Perceptrons

Perceptrons are thought to be good function approximators for Logic Gates. In this mini-tutorial, we will fit logic gates, AND & OR, with a perceptron!

| x1 | x2  | AND | OR |
| --- | ------ |:------:| ---- |
| 0 | 0  | 0 | 0 |
| 0 | 1  | 0 | 1 |
| 1 | 0  | 0 | 1 |
| 1 | 1  | 1 | 1 |

The task is to implement a simple **perceptron** to compute logical operations like AND, and OR.

- Input: $x_1$ and $x_2$
- Bias: $b = -1$ for AND; $b = 0$ for OR
- Weights: $w = [1, 1]$

with the following activation function:

$$
y = \begin{cases}
    \ 0 & \quad \text{if } w \cdot x + b \leq 0\\
    \ 1 & \quad \text{if } w \cdot x + b > 0
  \end{cases}
$$

We can define this threshold function in Python as:

In [7]:
def activation(z):
    if z > 0:
        return 1
    return 0

Let's define our X:

In [8]:
X = np.array([[0,0]
    ,[1,0]
    ,[0,1]
    ,[1,1]])

For AND we could implement a perceptron as:

In [11]:
w = np.array([1, 1])
b = -1

for x in X:
    a = activation(w.dot(x) + b)
    print(f'{x[0]} AND {x[1]}: {a}')

0 AND 0: 0
1 AND 0: 0
0 AND 1: 0
1 AND 1: 1


For OR we could implement a perceptron as:

In [12]:
w = np.array([1, 1])
b = 0
x = np.array([0, 0])

for x in X:
    a = activation(w.dot(x) + b)
    print(f'{x[0]} OR {x[1]}: {a}')

0 OR 0: 0
1 OR 0: 1
0 OR 1: 1
1 OR 1: 1


# Mini-Assignment

Can you implement a perceptron for 3 logic gates for the NOR operation?

# Training Perceptrons: Gradient Descent and Backpropagation

To update the weights of a perceptron $p$ given some data $x$ and loss function $L$, we use ***Gradient Descent***.

***Gradient Descent*** is a first-order gradient optimization algorithm. At first, the weights are randomly initialized, then the optimization algorithm takes repeated steps in the opposite direction of the gradient until it reaches a "satisfactory condition".

![SGD](resources/sgd.gif)

The gradient descent equation can be encapsulated in the following equation:

$$
w_{k+1} = w_{k} - \alpha \nabla L_{w}
$$

,where $L$ is the loss function and $\alpha$ is the learning rate.

***Backpropagation*** computes the gradient of a loss function with respect to the weights of the network $\nabla L_{w}$ for a single input–output example, and does so efficiently, computing the gradient one layer at a time, iterating backward from the last layer to avoid redundant calculations of intermediate terms in the chain rule.

Let's first define a simple loss function $L(w)$ for a perceptron $p$:

$$
L(w) = (target - y)^2
$$

$$
y = \sigma( \sum_k^{N} w_k x_k + b) 
$$

Compute the gradient for a perceptron, takes the following shape:

$$
\frac{\partial L}{\partial w_i} = \frac{\partial L}{\partial y} \frac{\partial y}{\partial \sigma} \frac{\partial \sigma}{\partial w_i}
$$

In this example, we fit a simple logic problem. We want to make the following predictions from the input:

| x1 | x2 | x3 | Output |
| - | - | - |:------:|
| 0 | 0 | 1  | 0      |
| 1 | 1 | 1  | 1      |
| 1 | 0 | 1  | 1      |
| 0 | 1 | 1  | 0      |

We will use *Numpy* to compute the network parameters, weights, activation, and outputs:

In [53]:
import numpy as np

We will use the *[Sigmoid](http://ml-cheatsheet.readthedocs.io/en/latest/activation_functions.html#sigmoid)* activation function:

In [3]:
def sigmoid(z):
    """The sigmoid activation function."""
    return 1 / (1 + np.exp(-z))

We could use the [ReLU](http://ml-cheatsheet.readthedocs.io/en/latest/activation_functions.html#activation-relu) activation function instead:

In [4]:
def relu(z):
    """The ReLU activation function."""
    return max(0, z)

The [Sigmoid](http://ml-cheatsheet.readthedocs.io/en/latest/activation_functions.html#sigmoid) activation function introduces non-linearity to the computation. It maps the input value to an output value between $0$ and $1$.

<img src="resources/SigmoidFunction1.png" style="max-width:100%; width: 30%; max-width: none">

The derivative of the sigmoid function is maximal at $x=0$ and minimal for lower or higher values of $x$:

<img src="resources/sigmoid_prime.png" style="max-width:100%; width: 25%; max-width: none">

The *sigmoid_prime* function returns the derivative of the sigmoid for any given $z$. The derivative of the sigmoid is $z * (1 - z)$. This is basically the slope of the sigmoid function at any given point: 

In [5]:
def sigmoid_prime(z):
    """The derivative of sigmoid for z."""
    return z * (1 - z)

### Mini-Assignment

What is the derivative of the ReLU activation function?

We define the inputs as rows in *X*. There are three input nodes (three columns per vector in $X$. Each row is one trainig example:

In [6]:
X = np.array([ [ 0, 0, 1 ],
               [ 0, 1, 1 ],
               [ 1, 0, 1 ],
               [ 1, 1, 1 ] ])
print(X)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


The outputs are stored in *y*, where each row represents the output for the corresponding input vector (row) in *X*. The vector is initiated as a single row vector and with four columns and transposed (using the $.T$ method) into a column vector with four rows:

In [7]:
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


To make the outputs deterministic, we seed the random number generator with a constant. This will guarantee that every time you run the code, you will get the same random distribution:

In [8]:
np.random.seed(1)

For our perceptron, we create a weight matrix ($Wo$) with randomly initialized weights:

TODO: Delve into how we initialize the network.

In [79]:
n_inputs = 3
n_outputs = 1
Wo = np.random.random( (n_inputs, n_outputs) ) * np.sqrt(2.0/n_inputs)
print(Wo)

[[0.43532763]
 [0.5649153 ]
 [0.25761743]]


The reason for the output weight matrix ($Wo$) to have 3 rows and 1 column is that it represents the weights of the connections from the three input neurons to the single output neuron. The initialization of the weight matrix is random with a mean of $0$ and a variance of $1$. There is a good reason for chosing a mean of zero in the weight initialization. See for details the section on Weight Initialization in the [Stanford course CS231n on Convolutional Neural Networks for Visual Recognition](https://cs231n.github.io/neural-networks-2/#init).


The core representation of this network is basically the weight matrix *Wo*. The rest, input matrix, output vector and so on are components that we need for learning and evaluation. The learning result is stored in the *Wo* weight matrix.

We loop in the optimization and learning cycle 10,000 times. In the *forward propagation* line we process the entire input matrix for training. This is called **full batch** training. I do not use an alternative variable name to represent the input layer, instead I use the input matrix $X$ directly here. Think of this as the different inputs to the input neurons computed at once. In principle the input or training data could have many more training examples, the code would stay the same.

This is the result of the perceptron without training:

In [80]:
sigmoid(np.dot(X, Wo))

array([[0.56405051],
       [0.6947737 ],
       [0.66662175],
       [0.77865756]])

Let's recall that the loss function is the squared error loss and using the perceptron gradient equation, our backpropagation equation would translate to:

$$
\frac{\partial L}{\partial w_i} = [ - 2 * (target - y)] * [\sigma'(\sum_k^{N} w_k x_k + b)] * [x_i] 
$$

After training with this gradient update equation, we will improve error on our perceptron model. 

Observe the error of our initialized perceptron model:

In [81]:
(y - sigmoid(np.dot(X, Wo)))**2

array([[0.31815298],
       [0.4827105 ],
       [0.11114106],
       [0.04899248]])

In [82]:
for n in range(10000):
    
    # forward propagation
    prediction = sigmoid(np.dot(X, Wo))
    
    # compute the loss
    loss_gradient = -2 * (y - prediction)
    
    # multiply the loss by the slope of the sigmoid at l1 (Backpropagation Step)
    l1_delta = sigmoid_prime(prediction) * loss_gradient
    gradients = np.dot(X.T, l1_delta)
    
    # update weights (Gradient Descent)
    Wo += - gradients
    


Now observe the error of our trained perceptron model:

In [83]:
(y - sigmoid(np.dot(X, Wo)))**2

array([[4.61951671e-05],
       [3.06376089e-05],
       [2.03748845e-05],
       [3.07354915e-05]])

This is the result of the perceptron with training:

In [84]:
sigmoid(np.dot(X, Wo))

array([[0.0067967 ],
       [0.00553513],
       [0.99548615],
       [0.99445604]])

# The Famous XOR Problem

The power of neural units comes from combining them into larger networks. Minsky and Papert (1969): A single neural unit cannot compute the simple logical function XOR.

With this narrow definition of a perceptron, it seems not possible to implement an XOR logic perceptron. The restriction is that there is a threshold function that is binary and piecewise linear.

As one student in my 2020 L645 class, Kazuki Yabe, points out, with a different activation function and a different weight vector, one unit can of course handle XOR. If we use the following activation function:

$$
y = \begin{cases}
    \ 0 & \quad \text{if } w \cdot x + b \neq 0.5\\
    \ 1 & \quad \text{if } w \cdot x + b = 0.5
  \end{cases}
$$

In [86]:
def bactivation(z):
    if z == 0.5:
        return 1
    else: return 0

If we assume the weights to be set to 0.5 and the bias to 0, one unit can handle the XOR logic:

- Input: $x_1$ and $x_2$
- Bias: $b = 0$ for XOR
- Weights: $w = [0.5, 0.5]$

In [88]:
w = np.array([0.5, 0.5])
b = 0
x = np.array([0, 0])
print("0 OR 0:", bactivation(w.dot(x) + b))
x = np.array([1, 0])
print("1 OR 0:", bactivation(w.dot(x) + b))
x = np.array([0, 1])
print("0 OR 1:", bactivation(w.dot(x) + b))
x = np.array([1, 1])
print("1 OR 1:", bactivation(w.dot(x) + b))

0 OR 0: 0
1 OR 0: 1
0 OR 1: 1
1 OR 1: 0


This particular activation function is of course not differentiable, and it remains to be shown that the weights can be learned, but nevertheless, a single unit can be identified that solves the XOR problem.

The difference between Minsky and Papert's (1969) definition of a perceptron and this unit is that - as Julia Hockenmaier pointed out - a perceptron is defined to have a decision function that would be binary and piecewise linear. This means that the unit that solves the XOR problem is not compatible with the definition of perceptron as in Minsky and Papert (1969) (p.c. Julia Hockenmaier).

## Revisiting Minsky and Papert (1969): The Tri-Perceptron XOR Solution

There is a proposed solution in [Goodfellow et al. (2016)](https://www.deeplearningbook.org/) for the XOR problem, using a network with two layers of ReLU-based units.

![XOR Network](resources/XOR_Network.png)

This two layer and three perceptron network solves the problem.

For more deiscussion on this problem, consult:

- [Wikipedia on the XOR problem](https://en.wikipedia.org/wiki/Perceptron)
- [Solving XOR with a single Perceptron](https://medium.com/@lucaspereira0612/solving-xor-with-a-single-perceptron-34539f395182)

# Multi-Layer Perceptron

**A Multi-Layer Perceptron is a model which consists of at least three layers of perceptrons: input layer, hidden layer, and output layer.**

![MLP](resources/mlp_hidden.jpeg)

How would backpropagation work in such a model?

![MLP_backprop](resources/mlp_backprop.png)

Consider the following dataset:

| Input  | Output |
| ------ |:------:|
| 0 0 1  | 0      |
| 0 1 1  | 1      |
| 1 0 1  | 1      |
| 1 1 1  | 0      |

The pattern here is a XOR pattern problem: If there is a $1$ in either column $1$ or $2$, but not in both, the output is $1$ (XOR over column $1$ and $2$).

To solve this problem, we need a network with another layer (MLP), that is a layer that will combine and transform the input, and an additional layer will map it to the output. We will add a *hidden layer* with randomized weights and then train those to optimize the output probabilities of the table above.

We will define a new $X$ input matrix that reflects the above table:

In [24]:
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])
print(X)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


We also define a new output matrix $y$:

In [25]:
y = np.array([[ 0, 1, 1, 0]]).T
print(y)

[[0]
 [1]
 [1]
 [0]]


We initialize the random number generator with a constant again:

In [26]:
np.random.seed(1)

Assume that our 3 inputs are mapped to 4 hidden layer ($Wh$) neurons, we have to initialize the hidden layer weights in a 3 by 4 matrix. The outout layer ($Wo$) is a single neuron that is connected to the hidden layer, thus the output layer is a 4 by 1 matrix:

In [27]:
n_inputs = 3
n_hidden_neurons = 4
n_output_neurons = 1
Wh = np.random.random( (n_inputs, n_hidden_neurons) )  * np.sqrt(2.0/n_inputs)
Wo = np.random.random( (n_hidden_neurons, n_output_neurons) )  * np.sqrt(2.0/n_hidden_neurons)
print("Wh:\n", Wh)
print("Wo:\n", Wo)

Wh:
 [[3.40497041e-01 5.88142486e-01 9.33866473e-05 2.46853512e-01]
 [1.19825683e-01 7.53941469e-02 1.52080826e-01 2.82149152e-01]
 [3.23959286e-01 4.39942021e-01 3.42270888e-01 5.59479379e-01]]
Wo:
 [[0.14456957]
 [0.62092279]
 [0.01936595]
 [0.47409212]]


We will loop now 100,000 times to optimize the weights:

In [28]:
for i in range(100000):
    l1 = sigmoid(np.dot(X, Wh))
    l2 = sigmoid(np.dot(l1, Wo))
    
    l2_error = y - l2
    
    if (i % 10000) == 0:
        print("Error:", np.mean(np.abs(l2_error)))
    
    # gradient, changing towards the target value
    l2_delta = l2_error * sigmoid_prime(l2)
    
    # compute the l1 contribution by value to the l2 error, given the output weights
    l1_error = l2_delta.dot(Wo.T)
    
    # direction of the l1 target:
    # in what direction is the target l1?
    l1_delta = l1_error * sigmoid_prime(l1)
    
    Wo += np.dot(l1.T, l2_delta)
    Wh += np.dot(X.T, l1_delta)

print("Wo:\n", Wo)
print("Wh:\n", Wh)

Error: 0.49962354308293877
Error: 0.010185068686370102
Error: 0.006740755437297383
Error: 0.005345052957883491
Error: 0.004547502999833713
Error: 0.004017450105072937
Error: 0.0036334495140870095
Error: 0.003339229754058863
Error: 0.003104745370932276
Error: 0.002912327550144696
Wo:
 [[-7.07355497]
 [14.20975817]
 [-7.01708617]
 [-7.15528258]]
Wh:
 [[ 6.66182717  6.80494448 -3.00320286  3.65642155]
 [-3.43419418  6.77518798  6.58168773  3.71366194]
 [ 0.59089835 -1.96151177  0.18071609 -5.62078292]]


# (WIP) Recurrent Neural Network

# Assignment: Reproducing Rosenblatt's NYT Experiment

![Times_July_13_Rosenblatt_Perceptron](resources/Times_July_13_Rosenblatt_Perceptron.png)